version: '3'

services:

  flask_server_api:
    container_name: flask_server_api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flask_server
    ports:
      - "8888:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/usr/src/flaskServer

  flask_server_celery:
    container_name: flask_server_celery
    image: flask_server
    volumes:
      - ./:/usr/src/flaskServer

    command: ['celery', '-A', 'celery_app', 'worker', '-l', 'info']

