version: '3'

services:

  flask_server:
    container_name: flask_server
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flask_server
    ports:
      - "8888:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/usr/src/flaskServer

