version: '3'

services:

  api:
    image: flask_server
    build:
      context: .
      dockerfile: ./Dockerfile

    restart: always
    container_name: flask_server_api

    ports:
      - "10002:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/usr/src/flaskServer

#  RabbitMq:
#    image: flask_server
#    restart: always
#    container_name: flask_server_RabbitMq
#
#    command:
#      - /bin/bash
#      - -c
#      - |
#        export PYTHONPATH=/usr/src/flaskServer
#        python rabbitmq/consumer_retry.py
